<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run</name>
   <tag></tag>
   <elementGuidId>5add8dd5-fc9f-46ca-8f86-542dd48281bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-MainContent']/div/div[11]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Run IndicatorIncrementIntervalJob&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d350fc7-18a9-4a22-9da1-300bb211ba49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary js-DisableOnClick</value>
      <webElementGuid>ebb9663a-f462-48c1-b064-4665ee2328fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95af493b-3279-4b68-bc02-5141a8c5a22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Run IndicatorIncrementIntervalJob</value>
      <webElementGuid>333e0337-2d3e-474b-a548-4528b2bf2789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Run IndicatorIncrementIntervalJob</value>
      <webElementGuid>61f0d56b-eade-41f0-82c6-4928d42416ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>b196823a-1c14-4587-90ac-a3ff8dc9a0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>69904870-f36e-419d-84ef-fabf173a75f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/jobs/20/run</value>
      <webElementGuid>a7df755b-9ec2-474f-8963-c26d55ee66bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run
</value>
      <webElementGuid>86e4bdff-d773-4681-b598-37f6cf6640b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-MainContent&quot;)/div[@class=&quot;inner-content&quot;]/div[@class=&quot;panel panel-default panel-table sub&quot;]/div[@class=&quot;panel-heading&quot;]/div[@class=&quot;extra-info&quot;]/a[@class=&quot;btn btn-primary js-DisableOnClick&quot;]</value>
      <webElementGuid>90697461-5d55-4cd3-9c78-dc56ef32745a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-MainContent']/div/div[11]/div/div/a</value>
      <webElementGuid>7b0c6624-f96f-4ceb-9bb3-508b6008e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Run')])[11]</value>
      <webElementGuid>252c0c59-a507-45f9-aef6-edc99ca81d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='less than 5 seconds'])[91]/following::a[1]</value>
      <webElementGuid>9fd36d79-dfce-43a8-9bf6-e6649292235c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tue, 10 Jun 2025 06:20:00 +0530 (29 days ago)'])[1]/following::a[1]</value>
      <webElementGuid>94c6e7fe-f79a-487c-aea8-86fe9399a3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IndicatorIncrementIntervalJob'])[1]/preceding::a[1]</value>
      <webElementGuid>a3fdbe33-6676-48c0-aa53-e837c60805e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[11]/preceding::a[1]</value>
      <webElementGuid>1006f484-5eed-4eb9-b0cb-107cc5811491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/jobs/20/run')]</value>
      <webElementGuid>f2b2f2d7-cf85-4865-9f17-7c2b7ad47574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/a</value>
      <webElementGuid>89beefc7-00d0-4605-97ab-10b93d8ff152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Run IndicatorIncrementIntervalJob' and @href = '/admin/jobs/20/run' and (text() = 'Run
' or . = 'Run
')]</value>
      <webElementGuid>5cc9b4b2-b8fd-4958-b158-ab62e1154b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
