<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Successfully created Control Action ID 280</name>
   <tag></tag>
   <elementGuidId>ea31430f-e239-40f9-aa43-061a21a4de5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5705b36-3fa7-4097-90f0-3e81c4d6841b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>cfcc8df5-95c9-4474-9b8d-7bf278a51feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully created Control Action ID #280</value>
      <webElementGuid>c895cbd7-8882-49d2-bb09-44d2e5347029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-Toaster&quot;)/div[@class=&quot;toaster&quot;]/div[@class=&quot;toast-container&quot;]/div[@class=&quot;toast success visible&quot;]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>6c37ffc6-028b-495d-816e-8544aee2dcc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-Toaster']/div/div/div/div</value>
      <webElementGuid>19e2fd6f-72ba-42f5-b6ad-8329e52b41fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[10]</value>
      <webElementGuid>b1081135-4542-4691-a86f-6b58e93f6523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert Type'])[1]/following::div[14]</value>
      <webElementGuid>570d5a54-2f2b-4ef4-94f0-a4ab80485a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Successfully created Control Action ID #280']/parent::*</value>
      <webElementGuid>bc4ddd5b-6f97-4cde-9203-fbca6a0d7780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div</value>
      <webElementGuid>ab33bc33-1d3f-4f17-bfd2-ec9e979640d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Successfully created Control Action ID #280' or . = 'Successfully created Control Action ID #280')]</value>
      <webElementGuid>83b0b493-4145-40f4-91b6-0bdf050bc195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
