<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_About this page_a-vj93gk7qrbz9</name>
   <tag></tag>
   <elementGuidId>1b562a36-dc51-4039-9017-9c5633491f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-vj93gk7qrbz9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-vj93gk7qrbz9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-vj93gk7qrbz9&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>405dd145-5da8-4abc-8ec2-7d5300f37f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>f8cf4f3d-88af-461a-9563-e70479827442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>cc97ff81-3469-4caf-ab31-890c6d300122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>271bbbab-392d-4681-b302-5adcc6140200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>859d2536-5b1d-427e-9515-457273c779f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-vj93gk7qrbz9</value>
      <webElementGuid>c3bf5f62-127d-411b-8900-63289d1dc8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>820a0935-3a00-4c8e-bef1-91c4e4a84350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7881e4d1-f639-4d49-b548-16bda4b2b192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>bbd3dd57-0694-4529-9c9d-898edb2fdabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdLLIMbAAAAAIl-KLj9p1ePhM-4LCCDbjtJLqRO&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=3jpV4E_UA9gZWYy11LtggjoU&amp;size=normal&amp;s=1W1STrrcLsnd9MtlsUwkNBGBkwO2_0CnUf52Tfli-gfRq1neXek2plpIu1qRS8mk1HtKPPU7AYFNQHyp9bBi7dxl2s0JE5MDzC0HXFyVP2ru9I2iOw4_2jpC1qxGSDg9S776-Re5SrZNciouZx4YjVQIS8oTi-cG0I54xMYMu8onxYa7jDDNUPORkStKEzDRXlZ9RW2VMTpb5NMp_9gD1goPOseCvsb7XRxXeHU8q7JUoJdQMpKGbb7jjUdoyUHe-MifUj5NgS7j0ed_oRwhHQYihrRzg2w&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=838haie5jc2h</value>
      <webElementGuid>5c21a0cd-c30f-491e-bfc3-50e9a0f732e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>a9c5f44e-ec02-44a5-89b9-eb1b99a0f6e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-vj93gk7qrbz9']</value>
      <webElementGuid>8d641987-dcb0-40a4-9848-3c8ff104bd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>ed844efe-4702-4736-a9b3-5961a08c5f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3b1dba20-fd75-4776-b830-fcfff89079a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-vj93gk7qrbz9' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdLLIMbAAAAAIl-KLj9p1ePhM-4LCCDbjtJLqRO&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=3jpV4E_UA9gZWYy11LtggjoU&amp;size=normal&amp;s=1W1STrrcLsnd9MtlsUwkNBGBkwO2_0CnUf52Tfli-gfRq1neXek2plpIu1qRS8mk1HtKPPU7AYFNQHyp9bBi7dxl2s0JE5MDzC0HXFyVP2ru9I2iOw4_2jpC1qxGSDg9S776-Re5SrZNciouZx4YjVQIS8oTi-cG0I54xMYMu8onxYa7jDDNUPORkStKEzDRXlZ9RW2VMTpb5NMp_9gD1goPOseCvsb7XRxXeHU8q7JUoJdQMpKGbb7jjUdoyUHe-MifUj5NgS7j0ed_oRwhHQYihrRzg2w&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=838haie5jc2h']</value>
      <webElementGuid>21ff63f4-195b-4ab3-b6ae-04f7db8f5aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
