<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_13323</name>
   <tag></tag>
   <elementGuidId>58bcdb7d-c25d-4a70-a76f-3af058fcf6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/indicator_responses/13323' and (text() = '13323' or . = '13323')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;13323&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01d2a135-f0a5-4b27-9e48-003f2b254ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indicator_responses/13323</value>
      <webElementGuid>5b57c522-1c48-433b-8f1f-483bce994ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13323</value>
      <webElementGuid>989c8d3d-78cc-4d4a-a4f8-5c431489ce03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-IndicatorResponseSubpanel&quot;)/div[@class=&quot;panel panel-default panel-table sub expanded&quot;]/div[@class=&quot;panel-body&quot;]/table[@class=&quot;table table-sortable&quot;]/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>413bb6f7-8638-4ca2-8d89-0b1f11b04937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>00741e99-a7c6-4ce9-9019-c0cad470f390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13323')]</value>
      <webElementGuid>7845079e-bdf2-4bd9-8e40-b855b8720019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Response'])[2]/following::a[1]</value>
      <webElementGuid>4a9c32b8-b387-4e4a-ad3c-9ce75fd5a168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Outcome'])[1]/preceding::a[1]</value>
      <webElementGuid>843886fd-8c9b-4a6a-9a64-c919dfebf303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Value'])[1]/preceding::a[1]</value>
      <webElementGuid>a7096097-4783-4486-a6d6-5968f949fab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13323']/parent::*</value>
      <webElementGuid>ee0a4fa3-931b-4233-b2d8-6a3ae46f27a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indicator_responses/13323')]</value>
      <webElementGuid>f95ca211-31e4-49d5-9c56-ddbda50ea916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>d5d9bd2d-3f7f-4128-b9db-73f6c399c628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indicator_responses/13323' and (text() = '13323' or . = '13323')]</value>
      <webElementGuid>c5843bf8-79fb-4235-82be-4a2bd8f5ca34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
