<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_13323</name>
   <tag></tag>
   <elementGuidId>58bcdb7d-c25d-4a70-a76f-3af058fcf6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/indicator_responses/13323' and (text() = '13323' or . = '13323')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;13323&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e610607b-255c-424a-b55e-6ac19ed551e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indicator_responses/13323</value>
      <webElementGuid>5a14839a-e06a-4e92-bd86-5af8f3b76f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13323</value>
      <webElementGuid>92411f62-3b02-4425-983a-7d412c499bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-IndicatorResponseSubpanel&quot;)/div[@class=&quot;panel panel-default panel-table sub expanded&quot;]/div[@class=&quot;panel-body&quot;]/table[@class=&quot;table table-sortable&quot;]/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>a29b7f03-a1ac-46c7-8753-45998e9894ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>45a93428-fcb6-4514-b7f7-c2358bd862fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13323')]</value>
      <webElementGuid>fe51cc09-88ef-4293-bdd2-b600ff97d1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Response'])[2]/following::a[1]</value>
      <webElementGuid>21cef62a-946a-47a1-934c-94d3f01c6087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Outcome'])[1]/preceding::a[1]</value>
      <webElementGuid>ebace960-94bb-4deb-8ab3-54b966534b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Value'])[1]/preceding::a[1]</value>
      <webElementGuid>163fcc13-8ba3-4bc9-acc4-22e1b8038009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13323']/parent::*</value>
      <webElementGuid>cbfe2a23-635b-4d67-996f-d7e6b4108780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indicator_responses/13323')]</value>
      <webElementGuid>6b5bd66a-a5af-4792-b262-1c95e550952d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>865ff14e-68f2-4be9-bfde-33531587dfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indicator_responses/13323' and (text() = '13323' or . = '13323')]</value>
      <webElementGuid>f4b73732-6eca-4adf-b17f-f38342f1aa83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
