<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_13323</name>
   <tag></tag>
   <elementGuidId>58bcdb7d-c25d-4a70-a76f-3af058fcf6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;13323&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ec4b62c-d7a9-489c-99f9-38036351728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indicator_responses/13323</value>
      <webElementGuid>2cec1cdf-959c-41bd-9f99-082d7716b9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13323</value>
      <webElementGuid>c66eea05-c125-4234-a46b-70f869d2cc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-IndicatorResponseSubpanel&quot;)/div[@class=&quot;panel panel-default panel-table sub expanded&quot;]/div[@class=&quot;panel-body&quot;]/table[@class=&quot;table table-sortable&quot;]/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>951cebc4-c352-4ed9-a0ef-27ef133b2fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-IndicatorResponseSubpanel']/div/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>100d7463-1fbe-4130-bf9b-73895375f337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13323')]</value>
      <webElementGuid>46feed30-0620-4e31-b53f-7748b3664d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Response'])[2]/following::a[1]</value>
      <webElementGuid>07d07515-b0a4-4fdc-8fed-870c0c9efd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Outcome'])[1]/preceding::a[1]</value>
      <webElementGuid>335cabe9-5555-4598-a04a-8bd3d7ef5cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Value'])[1]/preceding::a[1]</value>
      <webElementGuid>26b9a124-1151-4778-a67e-5d3ad9544870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13323']/parent::*</value>
      <webElementGuid>ca49d11b-f412-4220-b8f7-1208316efbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indicator_responses/13323')]</value>
      <webElementGuid>618fecba-eb4d-4dbc-9b19-09818be9a747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>37e57fa2-3efa-447e-b630-a62b61c5f6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indicator_responses/13323' and (text() = '13323' or . = '13323')]</value>
      <webElementGuid>bae67f80-3780-46f8-8eb4-b452e465d709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
